# Generated by Django 5.1.2 on 2024-10-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
        migrations.AlterModelOptions(
            name='personaldata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professionalexperience',
            options={},
        ),
    ]
